apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ud-reverse-proxy
  name: ud-reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: ud-reverse-proxy
  template:
    metadata:
      labels:
        service: ud-reverse-proxy
    spec:
      containers:
        - image: vabar/udagram-reverse-proxy
          name: ud-reverse-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
