version: "3"
services:
  ud-reverse-proxy:
    image: vabar/nginx-reverse-proxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - ud-api-user
      - ud-api-feed
  ud-api-user:
    image: vabar/udagram-api-user
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      AWS_BUCKET: $AWS_BUCKET
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  ud-api-feed:
    image: vabar/udagram-api-feed
   # Mount the shared configuration directory, used by the AWS CLI and AWS SDKs
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      AWS_BUCKET: $AWS_BUCKET
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  ud-frontend:
    image: vabar/udagram-frontend
    ports:
      - "8100:80"